services: 

  back-end:
    build: 
      context: urbansky-back
    working_dir: /usr/src/app
    volumes: 
      - ./urbansky-back:/usr/src/app
    tty: true
    ports: 
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1234
    command: npm run dev
    depends_on:
       - db

  front-end:
    build: 
      context: urbansky-front
    working_dir: /usr/src/app
    volumes: 
      - ./urbansky-front:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    command: npm run dev

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_API=postgres
